baseURL = 'https://matttelliott.com/bikemaps/'
languageCode = 'en-us'
title = 'Bike Maps'
theme = 'hugo-split-gallery'
cleanDestinationDir = true
publishDir = 'docs/'

[params]
  customCss = ["css/custom.css"]
  customJs = ["js/custom.js"]

footnote = '<a href="https://matttelliott.com">matttelliott.com</a>'
